# How does a player's blocking ability relate to their year in school? 

### We need to pull game-by-game records of player's blocks and minutes to figure this out. We'll include a couple of clauses to look only at 2017 and exclude stats for which our original dataset doesn't have a player's class recorded.

In [0]:
from pandas.io import gbq
project_id = '[YOUR_PROJECT_ID]'

In [0]:
query = """
SELECT
  class,
  SUM(blocks) AS blocks,
  SUM(minutes_int64) AS minutes,
  SUM(blocks)/SUM(minutes_int64) AS blocks_per_minute
FROM
  `bigquery-public-data.ncaa_basketball.mbb_players_games_sr`
WHERE
  class != ""
  AND season = 2017
GROUP BY
  class
ORDER BY
  blocks_per_minute DESC
"""

class_blocks = gbq.read_gbq(query=query, dialect ='standard', project_id=project_id)
class_blocks

Requesting query... ok.
Job ID: job_dEzpUoyqfoTNKwxgkIE8xx8vrMI5
Query running...
Query done.
Cache hit.

Retrieving results...
Got 5 rows.

Total time taken 0.57 s.
Finished at 2018-03-05 15:54:48.

  class  blocks  minutes  blocks_per_minute
0    JR   11242   640271           0.017558
1    FR    7077   416377           0.016997
2    GR     879    53633           0.016389
3    SR    9343   571305           0.016354
4    SO    7706   484026           0.015921